spring:
  application:
    name: Springsecurity
  datasource:
    url: jdbc:h2:mem:securitydb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080

# Logging (optional)
logging:
  level:
    org.springframework.security: INFO
    com.demo: DEBUG

# JWT Configuration (use a 64+ byte secret; this value is for development only)
jwt:
  secret: "A1b2C3d4E5f6G7h_A1b2C3d4E5f6G7h8A1b2C3d4E5f6G7h8A1b2C3d4E5f6G7h8"
  expiration: 3600000 # 1 hour in milliseconds
  tokenPrefix: "Bearer "

# Actuator exposure (limit to needed)
management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,prometheus"
  endpoint:
    shutdown:
      enabled: false